import QtQuick

QtObject {
    readonly property string wifiZero: "\uF101"
    readonly property string wifiOff: "\uF102"
    readonly property string wifiLow: "\uF103"
    readonly property string wifiHigh: "\uF104"
    readonly property string globeOff: "\uF105"
    readonly property string ethernetPort: "\uF106"
    readonly property string bluetoothOff: "\uF107"
    readonly property string bluetoothConnected: "\uF108"
    readonly property string aiAgent: "\uF109"
    readonly property string x: "\uF10A"
    readonly property string wifi: "\uF10B"
    readonly property string volume: "\uF10C"
    readonly property string volumeX: "\uF10D"
    readonly property string volume2: "\uF10E"
    readonly property string volume1: "\uF10F"
    readonly property string video: "\uF110"
    readonly property string videoOff: "\uF111"
    readonly property string sun: "\uF112"
    readonly property string sunMedium: "\uF113"
    readonly property string sunDim: "\uF114"
    readonly property string music: "\uF115"
    readonly property string mic: "\uF116"
    readonly property string micOff: "\uF117"
    readonly property string gamepad2: "\uF118"
    readonly property string earth: "\uF119"
    readonly property string chevronUp: "\uF11A"
    readonly property string chevronRight: "\uF11B"
    readonly property string chevronDown: "\uF11C"
    readonly property string check: "\uF11D"
    readonly property string boxes: "\uF11E"
    readonly property string bluetooth: "\uF11F"
    readonly property string arch: "\uF120"
}
