#    ▗▖ ▗▖ ▗▄▖ ▗▖   ▗▖   ▗▄▄▖  ▗▄▖ ▗▄▄▖ ▗▄▄▄▖▗▄▄▖ 
#    ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌ ▐▌
#    ▐▌ ▐▌▐▛▀▜▌▐▌   ▐▌   ▐▛▀▘ ▐▛▀▜▌▐▛▀▘ ▐▛▀▀▘▐▛▀▚▖
#    ▐▙█▟▌▐▌ ▐▌▐▙▄▄▖▐▙▄▄▖▐▌   ▐▌ ▐▌▐▌   ▐▙▄▄▖▐▌ ▐▌

# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/

wallpaper {
  monitor = 
  path = ~/Pictures/Wallpapers/current_wallpaper
  fit_mode = cover
}

#    ▗▖  ▗▖▗▄▄▄▖ ▗▄▄▖ ▗▄▄▖
#    ▐▛▚▞▜▌  █  ▐▌   ▐▌   
#    ▐▌  ▐▌  █   ▝▀▚▖▐▌   
#    ▐▌  ▐▌▗▄█▄▖▗▄▄▞▘▝▚▄▄▖

# https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/#misc-options

splash = false