# https://wiki.hypr.land/Configuring/

#    ▗▖  ▗▖ ▗▄▖ ▗▖  ▗▖▗▄▄▄▖▗▄▄▄▖▗▄▖ ▗▄▄▖  ▗▄▄▖
#    ▐▛▚▞▜▌▐▌ ▐▌▐▛▚▖▐▌  █    █ ▐▌ ▐▌▐▌ ▐▌▐▌   
#    ▐▌  ▐▌▐▌ ▐▌▐▌ ▝▜▌  █    █ ▐▌ ▐▌▐▛▀▚▖ ▝▀▚▖
#    ▐▌  ▐▌▝▚▄▞▘▐▌  ▐▌▗▄█▄▖  █ ▝▚▄▞▘▐▌ ▐▌▗▄▄▞▘                                           

# See https://wiki.hypr.land/Configuring/Monitors/

monitor=DP-4,1920x1080@165,0x0,1

#     ▗▄▖ ▗▖ ▗▖▗▄▄▄▖▗▄▖  ▗▄▄▖▗▄▄▄▖▗▄▖ ▗▄▄▖▗▄▄▄▖
#    ▐▌ ▐▌▐▌ ▐▌  █ ▐▌ ▐▌▐▌     █ ▐▌ ▐▌▐▌ ▐▌ █  
#    ▐▛▀▜▌▐▌ ▐▌  █ ▐▌ ▐▌ ▝▀▚▖  █ ▐▛▀▜▌▐▛▀▚▖ █  
#    ▐▌ ▐▌▝▚▄▞▘  █ ▝▚▄▞▘▗▄▄▞▘  █ ▐▌ ▐▌▐▌ ▐▌ █  

exec-once = hyprpaper
exec-once = hyprsunset
exec-once = xdg-desktop-portal-hyprland
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = quickshell

#    ▗▄▄▄▖▗▖  ▗▖▗▖  ▗▖
#    ▐▌   ▐▛▚▖▐▌▐▌  ▐▌
#    ▐▛▀▀▘▐▌ ▝▜▌▐▌  ▐▌
#    ▐▙▄▄▖▐▌  ▐▌ ▝▚▞▘ 

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct

#    ▗▄▄▖ ▗▄▄▄▖▗▄▄▖ ▗▖  ▗▖▗▄▄▄▖ ▗▄▄▖ ▗▄▄▖▗▄▄▄▖ ▗▄▖ ▗▖  ▗▖ ▗▄▄▖
#    ▐▌ ▐▌▐▌   ▐▌ ▐▌▐▛▚▞▜▌  █  ▐▌   ▐▌     █  ▐▌ ▐▌▐▛▚▖▐▌▐▌   
#    ▐▛▀▘ ▐▛▀▀▘▐▛▀▚▖▐▌  ▐▌  █   ▝▀▚▖ ▝▀▚▖  █  ▐▌ ▐▌▐▌ ▝▜▌ ▝▀▚▖
#    ▐▌   ▐▙▄▄▖▐▌ ▐▌▐▌  ▐▌▗▄█▄▖▗▄▄▞▘▗▄▄▞▘▗▄█▄▖▝▚▄▞▘▐▌  ▐▌▗▄▄▞▘

# See https://wiki.hypr.land/Configuring/Permissions/

#    ▗▖ ▗▖▗▄▄▄▖
#    ▐▌ ▐▌  █  
#    ▐▌ ▐▌  █  
#    ▝▚▄▞▘▗▄█▄▖

source = ./conf/ui.conf

#    ▗▖  ▗▖▗▄▄▄▖ ▗▄▄▖ ▗▄▄▖
#    ▐▛▚▞▜▌  █  ▐▌   ▐▌   
#    ▐▌  ▐▌  █   ▝▀▚▖▐▌   
#    ▐▌  ▐▌▗▄█▄▖▗▄▄▞▘▝▚▄▄▖
                
# https://wiki.hypr.land/Configuring/Variables/#misc     

misc {
  vrr = true

  force_default_wallpaper = 0
  disable_hyprland_logo = true
  
  # for browser focus on link click
  focus_on_activate = true
}

#    ▗▄▄▄▖▗▖  ▗▖▗▄▄▖ ▗▖ ▗▖▗▄▄▄▖
#      █  ▐▛▚▖▐▌▐▌ ▐▌▐▌ ▐▌  █  
#      █  ▐▌ ▝▜▌▐▛▀▘ ▐▌ ▐▌  █  
#    ▗▄█▄▖▐▌  ▐▌▐▌   ▝▚▄▞▘  █  

# https://wiki.hypr.land/Configuring/Variables/#input

input {
  kb_layout = us,ru
  kb_options = grp:alt_shift_toggle

  follow_mouse = 1
  
  sensitivity = -0.3
  accel_profile = flat
}
cursor {
  no_warps = true
}

#    ▗▖ ▗▖▗▄▄▄▖▗▖  ▗▖▗▄▄▖ ▗▄▄▄▖▗▖  ▗▖▗▄▄▄ ▗▄▄▄▖▗▖  ▗▖ ▗▄▄▖ ▗▄▄▖
#    ▐▌▗▞▘▐▌    ▝▚▞▘ ▐▌ ▐▌  █  ▐▛▚▖▐▌▐▌  █  █  ▐▛▚▖▐▌▐▌   ▐▌   
#    ▐▛▚▖ ▐▛▀▀▘  ▐▌  ▐▛▀▚▖  █  ▐▌ ▝▜▌▐▌  █  █  ▐▌ ▝▜▌▐▌▝▜▌ ▝▀▚▖
#    ▐▌ ▐▌▐▙▄▄▖  ▐▌  ▐▙▄▞▘▗▄█▄▖▐▌  ▐▌▐▙▄▄▀▗▄█▄▖▐▌  ▐▌▝▚▄▞▘▗▄▄▞▘

# See https://wiki.hypr.land/Configuring/Keywords/

source = ./conf/keybindings.conf

#    ▗▖ ▗▖ ▗▄▖ ▗▄▄▖ ▗▖ ▗▖ ▗▄▄▖▗▄▄▖  ▗▄▖  ▗▄▄▖▗▄▄▄▖ ▗▄▄▖
#    ▐▌ ▐▌▐▌ ▐▌▐▌ ▐▌▐▌▗▞▘▐▌   ▐▌ ▐▌▐▌ ▐▌▐▌   ▐▌   ▐▌   
#    ▐▌ ▐▌▐▌ ▐▌▐▛▀▚▖▐▛▚▖  ▝▀▚▖▐▛▀▘ ▐▛▀▜▌▐▌   ▐▛▀▀▘ ▝▀▚▖
#    ▐▙█▟▌▝▚▄▞▘▐▌ ▐▌▐▌ ▐▌▗▄▄▞▘▐▌   ▐▌ ▐▌▝▚▄▄▖▐▙▄▄▖▗▄▄▞▘

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

layerrule {
  name = quickshell-blur
  match:namespace = quickshell

  blur = 1
}

windowrule {
  name = suppress-maximize
  match:class = .*

  suppress_event = maximize
}

windowrule {
  name = xwayland-float-no-focus
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0

  no_focus = 1
}

windowrule {
  name = floation-pip
  match:title = ^(Picture-in-Picture)$

  float = 1
  pin = 1
  size = 440 247
  move = 10 10
}

windowrule {
  name = copilot-cli-float
  match:class = ^(copilot-cli)$

  animation = slide left
  float = 1
  pin = 1
  opacity = 0.9
}

# Speacial workspaces
windowrule {
  name = switch-to-browser
  match:class = ^(zen.*)$

  workspace = 10
}
windowrule {
  name = switch-to-music
  match:class = ^(spotify.*)$

  workspace = 11
}
windowrule {
  name = switch-to-steam
  match:title = ^(Steam)$

  workspace = 12
}